using System;
using JetBrains.Annotations;

namespace UI.ListItems
{
	public enum SoundType
	{
		[UsedImplicitly]
		PressCrush,
		[UsedImplicitly]
		UIElementClick,
		[UsedImplicitly]
		UIBuyItemClick,
        [UsedImplicitly]
		UIBoostRewardedItemClick,
		[UsedImplicitly]
		UILevelUpClick,
		[UsedImplicitly]
		UIBoostMoneyClick,
		[UsedImplicitly]
		UIBoostSpeedClick,
		[UsedImplicitly]
		UICollectMoneyClick,
		[UsedImplicitly]
		UICollectMoneyRewardedClick,
		[UsedImplicitly]
		ScreenTap,
		[UsedImplicitly]
		OreBreak,
		[UsedImplicitly]
		OreHitConveyor,
		[UsedImplicitly]
		ConveyorWorkCycle1,
		[UsedImplicitly]
		MoneyIncrease,
		[UsedImplicitly]
		BoostMoney,
		[UsedImplicitly]
		BoostSpeed,
		[UsedImplicitly]
		SmeltersWork1,
		[UsedImplicitly]
		SmeltersWork2,
		[UsedImplicitly]
		OreFallToSmelters1,
		[UsedImplicitly]
		OreFallToSmelters2,
		[UsedImplicitly]
		BarHitConveyour,
		[UsedImplicitly]
		ConveyorWorkCycle2,
        [UsedImplicitly]
        UIBuyFruitClick,
        [UsedImplicitly]
        UIReadyLevelUp,
        [UsedImplicitly]
        BottleSpawn,
    }
}
